### ISSUE TITLE
All properties from tags removed after recent update

### ISSUE THREAD

**Issue by janaengelhardt** [amplitude/amplitude-browser-sdk-gtm-template#50]
After the recent update from 3rd May I can't see any set properties in my tags anymore

**Comment by yuhao900914** [comment]
@janaengelhardt 
This was not intentional. I do apologize for the inconvenience. Thanks for your feedback. We appreciate that.
`any set properties` I think you mean the event properties. The name of that field has been changed. We revert that back in the latest version. However, if you already updated the template to previous version (c811447), you might need to reconfige it again in the latest version(0da509c).
