### ISSUE TITLE
Event Properties accepting an Data Layer object var?

### ISSUE THREAD

**Issue by coluccini** [amplitude/amplitude-browser-sdk-gtm-template#7]
Hi!
I'm updating our GTM implementation to start using this template, but our implementation is based on sending all events properties in one single Data Layer object and then passing it as it is to amplitude sdk. This way we can have a generic Tag on GTM that can track any event type with it corresponding properties without needing to set a specific tag/trigger per each event. 
The generic tag was:

`<script>amplitude.getInstance().logEvent('{{eventType}}', {{eventProperties}});</script>`

Where both, `{{eventType}}` and `{{eventProperties}}`, are an String and a Object sent to Data Layer from our app (we also have specific tags for more special events, but we use this for more simple event).

If I not seeing it wrong, the template force me to know in advance all the properties any event will have, so I would need to add a tag for every single event we would like to track. Is there a way to just pass the whole object having the properties?

Thanks!

**Comment by yuhao900914** [comment]
Hi @coluccini, 
1. Which GTM template are you using? Are you using `Amplitude Analytics Legacy` or `Amplitude Analytics Browser SDK`? The example you showed is using the legacy template, but this is GitHub repo is for the `Amplitude Analytics Browser SDK`.
2. Currently, amplitude GTM templates don't support the generic events and properties out of the box. But there has some way for the workaround.  

All those workarounds required a third-party dependency. And all of those dependencies are not belong to amplitude. So amplitude is not responsible for either of them. Here is just an example.

Workaround 1: If you are using the `Amplitude Analytics Browser SDK`. The init tag is separated from other tag types, like track, etc. Then you only need to set up an `init` tag. And ensure the init tag is executed before other tags(in the sequence section). Then you can use the amplitude SDK on other custom scripts. There has a [data layer helper ](https://github.com/google/data-layer-helper)developed by google, which can be used to monitor the data layer. With the data layer helper, you are able to catch all the objects has been sent to the data layer. Then you can create a custom tag and add the data layer helper, then call `amplitude.track` in this custom tag to track events with different event types and event properties.

Workaround 2: There is another way to do but there have some limitations. a. You need to define the trigger with the `Custom Event` type. The event name would be `*` in order to catch all the different names.  [More reference](https://www.simoahava.com/gtm-tips/use-all-events-trigger-more-control/). You can add some regex rules to filter the events you don't want to catch. b. I know there has a library that can exact the entire contents of the object that was pushed into the dataLayer. It can be used to catch generic properties.  For example, the [data layer picker](https://www.simoahava.com/custom-templates/data-layer-picker/). You can use this as your variable template. And in the amplitude tag, you can use this variable as the properties value. The limitation here is you still need to define a property name. And it will be the prefix to all the properties' names.



This is the screenshot for the custom event trigger:
<img width="1174" alt="custom-event" src="https://user-images.githubusercontent.com/13028329/224408393-4f9d325b-1200-4947-bfec-5d5df592d65d.png">
This is the variable template:
<img width="1247" alt="variable-template" src="https://user-images.githubusercontent.com/13028329/224407175-a39c6089-349c-4e47-8328-8089119fe188.png">
This is how the amplitude tag looks like:
<img width="1245" alt="amplitude-log" src="https://user-images.githubusercontent.com/13028329/224407419-b0e12073-08bb-4c2e-b027-bdbbdc605d84.png">
